### ISSUE TITLE
api function to check if picker is being displayed.

### ISSUE THREAD

**Issue by rodrigoaguilera** [EastDesire/jscolor#32]
I want the button that opens the picker, meaning the target element in the following code:
```
var myPicker = new JSColor(<targetElement>, <options>)
```
to also close the picker when is open. 
I think that a `isShown` method on the instance can be handy for this.

**Comment by EastDesire** [comment]
Hi @rodrigoaguilera , you can actually check target element's classList to see whether it contains class `jscolor-active`, which means that the color picker is shown on it.

For your use case, the code would be something like this:
```html
<button id="myPicker" data-jscolor="{showOnClick: false}" onclick="this.jscolor[this.classList.contains('jscolor-active') ? 'hide' : 'show']()">
Click me
</button>
```
(Note that we disabled the default onclick handler here, so that it doesn't interfere with custom show/hide call.)

Please let me know if it does the trick for you.

**Comment by rodrigoaguilera** [comment]
Thanks for the answer. Exactly what I wanted
